[package]
name = "day-9"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aoc-lib = { path = "../aoc-lib" }

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "bench"
harness = false
